#!/usr/bin/env bash
# Consolidate every Leto credential into ONE env file: ~/.config/leto/leto.env
#
# Sources:
#   ~/.config/leto/{linear-api-key,slack-bot-token,slack-app-token,slack-user-token}
#   ~/.claude/scheduled-tasks/youtrack-daily-digest/.env   (YOUTRACK_BASE_URL, YOUTRACK_TOKEN)
#
# Prints KEY NAMES ONLY — never a value. Idempotent: backs up any existing
# leto.env first, and never deletes a legacy file (that is your call, after
# `hooks/leto_secrets.py --check` says everything still authenticates).
#
# Usage:
#   bash ~/Projects/Leto/scripts/migrate-secrets.sh            # write
#   bash ~/Projects/Leto/scripts/migrate-secrets.sh --dry-run  # show what it would do

set -euo pipefail

CFG="$HOME/.config/leto"
ENV_FILE="$CFG/leto.env"
YT_ENV="$HOME/.claude/scheduled-tasks/youtrack-daily-digest/.env"
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# key:legacy-basename for the four single-value files
LEGACY_MAP=(
  "LINEAR_API_KEY:linear-api-key"
  "SLACK_BOT_TOKEN:slack-bot-token"
  "SLACK_APP_TOKEN:slack-app-token"
  "SLACK_USER_TOKEN:slack-user-token"
)

declare -a FOUND_KEYS=() FOUND_SRC=()
BODY=""

add_key() {  # add_key KEY VALUE SOURCE_LABEL
  local key="$1" val="$2" src="$3"
  [[ -z "$val" ]] && return 0
  BODY+="export ${key}=${val}"$'\n'
  FOUND_KEYS+=("$key")
  FOUND_SRC+=("$src")
}

# ── 1. the four legacy single-value files ────────────────────────────────────
for entry in "${LEGACY_MAP[@]}"; do
  key="${entry%%:*}"; base="${entry#*:}"
  path="$CFG/$base"
  [[ -f "$path" ]] || continue
  add_key "$key" "$(tr -d '[:space:]' < "$path")" "legacy:$base"
done

# ── 2. the separate youtrack .env (parsed, not sourced) ──────────────────────
if [[ -f "$YT_ENV" ]]; then
  for key in YOUTRACK_BASE_URL YOUTRACK_TOKEN; do
    # BSD/macOS sed is BRE-only — no GNU `\+`. Use [[:space:]][[:space:]]*.
    val="$(sed -n "s/^[[:space:]]*\(export[[:space:]][[:space:]]*\)\{0,1\}${key}[[:space:]]*=[[:space:]]*//p" \
           "$YT_ENV" | head -1 | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//" \
           -e 's/[[:space:]]*$//')"
    add_key "$key" "$val" "youtrack/.env"
  done
else
  echo "note: no youtrack .env at $YT_ENV — skipping its two keys" >&2
fi

if [[ ${#FOUND_KEYS[@]} -eq 0 ]]; then
  echo "error: found no credentials to migrate. Nothing written." >&2
  exit 1
fi

HEADER="# Leto secrets — every credential in one place.
# Generated by scripts/migrate-secrets.sh on $(date -Iseconds)
# Template + provenance for each key: ~/Projects/Leto/.env.example
# Validate:  python3 ~/Projects/Leto/hooks/leto_secrets.py --check
"

if $DRY_RUN; then
  echo "DRY RUN — would write ${#FOUND_KEYS[@]} keys to $ENV_FILE (mode 600):"
else
  mkdir -p "$CFG"; chmod 700 "$CFG"
  if [[ -f "$ENV_FILE" ]]; then
    backup="$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
    cp -p "$ENV_FILE" "$backup"
    echo "backed up existing env file -> $backup" >&2
  fi
  # Write with a restrictive umask so the value is never briefly world-readable.
  ( umask 077; printf '%s\n%s' "$HEADER" "$BODY" > "$ENV_FILE" )
  chmod 600 "$ENV_FILE"
  echo "wrote ${#FOUND_KEYS[@]} keys to $ENV_FILE (mode 600):"
fi

for i in "${!FOUND_KEYS[@]}"; do
  printf '  %-20s from %s\n' "${FOUND_KEYS[$i]}" "${FOUND_SRC[$i]}"
done

cat <<'EOF'

Next:
  1. Replace LINEAR_API_KEY — the migrated one is DEAD (401 since 2026-08-24).
     Linear -> Settings -> Security & access -> New API key, then edit the
     export LINEAR_API_KEY= line in ~/.config/leto/leto.env.
  2. Verify:  python3 ~/Projects/Leto/hooks/leto_secrets.py --check
  3. Only once that is all green, remove the legacy files:
       rm ~/.config/leto/{linear-api-key,slack-bot-token,slack-app-token,slack-user-token}
     (Consumers fall back to them until then, so there is no rush.)
EOF
